name: Lints
on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
